name: "skelworkflow CI"

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install ShellCheck"
        run: sudo apt-get install -y shellcheck

      - name: "Lint script"
        run: shellcheck skelworkflow.sh

      - name: "Test for script"
        run: ./skelworkflow.sh testskel main
